apiVersion: apps/v1
kind: Deployment
metadata:
  name: rick-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rick-api
  template:
    metadata:
      labels:
        app: rick-api
    spec:
      containers:
        - name: rick-api
          image: rick-api
          imagePullPolicy: Never
          ports:
            - containerPort: 5050

