replicaCount: 1

image:
  repository: rick-api
  tag: "latest"
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: rick.local

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

probes:
  liveness:
    path: /healthcheck
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    path: /healthcheck
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10

